name: Update staging branch

on:
  push:
    branches:
      - site9-**-newcart
      - site9-**-newtheme
  workflow_dispatch:

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Merge development -> staging
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: ${{steps.vars.outputs.short_ref}}
          target_branch: staging/${{steps.vars.outputs.short_ref}}
          github_token: ${{secrets.PAT_TOKEN}}
