# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - site9-**-newcart
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge client master -> client staging
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: ${GITHUB_REF##*/}
          target_branch: staging/${GITHUB_REF##*/}
          github_token: ${{ secrets.PAT_TOKEN }}

#       - name: Merge staging -> uat
#         uses: devmasx/merge-branch@v1.3.1
#         with:
#           type: now
#           from_branch: staging
#           target_branch: uat
#           github_token: ${{ github.token }}
