name: Create staging branches

on: create

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Create branches
    steps:
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Create branch
        if: startsWith(github.event.ref, 'site9-') && endsWith(github.event.ref, '-newcart') || endsWith(github.event.ref, '-newtheme')
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          branch: staging/${{github.event.ref}}
